package resources;
// Generated 18.Ara.2011 01:25:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Kisi generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "kisi", catalog = "ogrenci")
public class Kisi implements java.io.Serializable {

	private int id;
	private String adi;
	private String soyadi;


	public Kisi() {
	}

	public Kisi(int id, String adi, String soyadi) {
		this.id = id;
		this.adi = adi;
		this.soyadi = soyadi;
	}



	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "adi", nullable = false, length = 20)
	public String getAdi() {
		return this.adi;
	}

	public void setAdi(String adi) {
		this.adi = adi;
	}

	@Column(name = "soyadi", nullable = false, length = 20)
	public String getSoyadi() {
		return this.soyadi;
	}

	public void setSoyadi(String soyadi) {
		this.soyadi = soyadi;
	}


}
